version: '3.8'
  
services: 

  router01:
    image: mongo:5.0.11
    container_name: router-01
    hostname: router01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all

  router02:
    image: mongo:5.0.11
    container_name: router-02
    hostname: router02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    links:
      - router01


  configsvr01:
    image: mongo:5.0.11
    container_name: configsvr01
    hostname: configsvr01
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    links:
      - shard01-a
      - shard02-a
      - shard03-a

  configsvr02:
    image: mongo:5.0.11
    container_name: configsvr02
    hostname: configsvr02
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    links:
      - configsvr01

  configsvr03:
    image: mongo:5.0.11
    container_name: configsvr03
    hostname: configsvr03
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    links:
      - configsvr02

  
  shard01-a:
    image: mongo:5.0.11
    container_name: shard-01-a
    hostname: shard01-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    links:
      - shard01-b
      - shard01-c

  shard01-b:
    image: mongo:5.0.11
    container_name: shard-01-b
    hostname: shard01-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01

  shard01-c:
    image: mongo:5.0.11
    container_name: shard-01-c
    hostname: shard01-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01


  shard02-a:
    image: mongo:5.0.11
    container_name: shard-02-a
    hostname: shard02-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    links:
      - shard02-b
      - shard02-c

  shard02-b:
    image: mongo:5.0.11
    container_name: shard-02-b
    hostname: shard02-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02

  shard02-c:
    image: mongo:5.0.11
    container_name: shard-02-c
    hostname: shard02-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02


  shard03-a:
    image: mongo:5.0.11
    container_name: shard-03-a
    hostname: shard03-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    links:
      - shard03-b
      - shard03-c

  shard03-b:
    image: mongo:5.0.11
    container_name: shard-03-b
    hostname: shard03-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03

  shard03-c:
    image: mongo:5.0.11
    container_name: shard-03-c
    hostname: shard03-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
