version: '3.7'

services:

  clickhouse:
    container_name: clickhouse
    hostname: clickhouse
    image: yandex/clickhouse-server:21.3.20-alpine
    volumes:
      - ./datasets:/datasets
      - ./init.sh:/init.sh
      - ./test.sh:/test.sh
