version: '3.8'

services:

  manticore1:
    container_name: manticore1
    hostname: manticore1
    image: manticoresearch/manticore:5.0.2-extra
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    networks:
      - manticore

  manticore2:
    container_name: manticore2
    hostname: manticore2
    image: manticoresearch/manticore:5.0.2-extra
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    networks:
      - manticore

  manticore3:
    container_name: manticore3
    hostname: manticore3
    image: manticoresearch/manticore:5.0.2-extra
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    networks:
      - manticore

networks:
  manticore:
    driver: bridge
